"""
Snakefile for running phage assembly from Hecatomb QC'd reads.

Rachel Rodgers, June 2021

Updating for new HTCF cluster October 2022.
"""

import os
import sys

#----- Snakemake Set Up -----#

configfile: "./config/phage_pipeline_config.yaml"

# Paths
HECATOMB_DIR = config["Paths"]["Hecatomb"]

#----- Collect the Input Files -----#

# Pull sample names from the Hecatomb step 7 QC'd files and store in list
SAMPLES, = glob_wildcards(os.path.join(HECATOMB_DIR, "results", "QC", "step_7", "{sample}_R1.s7.out.fastq"))

#----- Rules -----#

rule all:
	input:
		#os.path.join("results", "contig_abundance_table", "contig_abundance_table.txt"),
		expand(os.path.join("results", "quantification", "{sample}.rpkm"), sample = SAMPLES),
		os.path.join("results", "mmseqs_phageDB_results", "GPD_search_results", "GPD_results_bestHit.m8"),
		os.path.join("results", "mmseqs_phageDB_results", "GVD_search_results", "GVD_results_bestHit.m8"),
		os.path.join("results", "mmseqs_phageDB_results", "MGV_search_results", "MGV_results_bestHit.m8"),
		os.path.join("results", "mmseqs_NT_results", "NT_search_results", "NT_results_bestHit.m8")
		
#----- Snakemake Workflow -----#

#----- Build Contig Dictionary -----#
include: "./rules/build_contig_dictionary.smk"

#----- Build Reference From Contig Dictionary for Quantification By Mapping -----#
include: "./rules/quantify_contig_dictionary.smk"

#----- Generate MMSeqs DBs from Contig Dictionary & Phage DBs -----#
include: "./rules/create_phage_databases.smk"

#----- MMSeqs2 Translated Seach (tBLASTx) Contig Dictionary against the Gut Phage DB (GPD) -----#
include: "./rules/query_GPD.smk"

#----- MMSeqs2 Translated Seach (tBLASTx) Contig Dictionary against the Human Gut Virome DB (GVD) -----#
include: "./rules/query_GVD.smk"

#----- MMSeqs2 Translated Seach (tBLASTx) Contig Dictionary against the Metagenomic Gut Virus (MGV) Catalog -----#
include: "./rules/query_MGV.smk"

#----- Select Probable Phage Contigs from the MMSeqs Results -----#
include: "./rules/select_phage_contigs_for_NT.smk"

#----- Extract the Probable Phage Contig Sequences to a New File to Query against NT with MMSeqs2 -----#
include: "./rules/extract_contigs_for_NT.smk"

#----- Untranslated (blastn) MMSeqs2 Search of Probable Phage Contigs against NT -----#
include: "./rules/query_NT.smk"
