---
Paths:
  Hecatomb: /scratch/mtblab/rachel/Holtz_eLABE/Hecatomb_Run_210511/Hecatomb-HTCF-Snake

DBs:
  GVD: /opt/apps/labs/mtblab/databases/phage-pipeline/resources/Gut_Virome_Database/GVDv1_viralpopulations.fna
  GPD: /opt/apps/labs/mtblab/databases/phage-pipeline/resources/Gut_Phage_Database/GPD_sequences.fa
  MGV: /opt/apps/labs/mtblab/databases/phage-pipeline/resources/Metagenomic_Gut_Virus_Catalog/mgv_contigs.fna
  NT: /scratch/mtblab/rachel/mmseqs_NT_db/mmseqs_NT

Tools:
  BBTools: bbtools/38.26
  SeqKit: seqkit/0.10.1
  Flye: py-flye/2.8.1-python-3.6.5
  R: r/3.6.3-python-3.6.5-java-11
  metaSPAdes: spades/3.14.0-python-2.7.15
  BLAST: /opt/apps/labs/mtblab/software/ncbi-blast-2.11.0+/bin
  megahit: megahit/1.1.4
  MMSeqs2: mmseqs2/13-45111
