---
Paths:
  Hecatomb: ../somya_mouse_poop_vlps/hecatomb
  CT2_template: /scratch/mtblab/rachel/Phage-Pipeline-HTCF-Snake/phage_CT2_template.sbt
  CT2_path: /opt/apps/labs/mtblab/software

Tools:
  BBTools: bbtools/38.26
  megahit: megahit/1.1.4
  SeqKit: seqkit/0.10.1
  flye: py-flye/2.8.1-python-3.6.5
  R: r/3.6.3-python-3.6.5-java-11
