---
Paths:
  Hecatomb: /scratch/mtblab/rachel/Holtz_MOMS/Hecatomb-HTCF-Snake

DBs:
  GVD: /ref/lhlab/data/phage_pipeline_databases/Gut_Virome_Database/GVDv1_viralpopulations.fna
  GPD: /ref/lhlab/data/phage_pipeline_databases/Gut_Phage_Database/GPD_sequences.fa
  MGV: /ref/lhlab/data/phage_pipeline_databases/Metagenomic_Gut_Virus_Catalog/mgv_contigs.fna
  NT: /ref/lhlab/data/phage_pipeline_databases/mmseqs_NT/mmseqs_NT_db

Tools:
  BBTools: /ref/mtblab/software/bbmap_38.96/bbmap/
  SeqKit: eval $( spack load --sh seqkit@0.10.1 )
  Flye: conda activate flye_2.9.1
  R: eval $( spack load --sh r@4.1.1 )
  metaSPAdes: spades/3.14.0-python-2.7.15
  BLAST: /opt/apps/labs/mtblab/software/ncbi-blast-2.11.0+/bin
  megahit: conda activate megahit_1.2.9
  MMSeqs2: /ref/mtblab/software/mmseqs/bin/mmseqs
