---
Paths:
  Hecatomb: /scratch/mtblab/rachel/Phage-Pipeline-HTCF-Snake/test_data
  CT2_template: /scratch/mtblab/rachel/Phage-Pipeline-HTCF-Snake/dummy_template.sbt
  CT2: /ref/mtblab/software/Cenote-Taker2

Tools:
  CT2: eval "$(conda shell.bash hook)"; conda activate cenote-taker2_2.1.5_env
  BBTools: eval $( spack load --sh bbmap@38.63 )
  megahit: eval "$(conda shell.bash hook)"; conda activate megahit_1.2.9
  SeqKit: eval $( spack load --sh seqkit@0.10.1 )
  flye: eval "$(conda shell.bash hook)"; conda activate flye_2.9.1
  R: eval $( spack load --sh r@4.1.1 )
